### ISSUE TITLE
Tentative Excalibur v1.0.0 Roadmap

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#1161]
## v1 Roadmap

Roadmap is subject to change and not 100% complete

### v0.23.0 - Collision Refactor and Enhancements
* [x] Collision Refactoring #1119 
* [x] Within/closestLine implementation #1071 
* [x] Re-implement collision groups #862 #1091 
      * [Collision Group Sample Platformer](https://github.com/excaliburjs/sample-platformer)
* [x] Bugs, bugs, bugs

### v0.24.0 

* [ ] ECS foundations
* [ ] Drawing API redesign
   * [ ] Remove child actors in favor of heirarchical drawing
* [ ] Switch polyfills to CoreJS
* [ ] TypeScript
   * [ ] Switch to ESLint over TSLint
   * [ ] TypeScript 3.5
   * [ ] `strict: true`
* [ ] Build speed improvement
* [ ] Bugs, bugs, bugs

### v0.25.0

* [ ] ECS Everywhere
* [ ] Action Redo async/await
* [ ] Multi-contact collisions
* [ ] Incremental loading
* [ ] Shared vs Scene scoped resources to save memory
* [ ] Bugs, bugs, bugs

### v0.26.0

* [ ] API standardization
* [ ] Style guide finalization
* [ ] Game state management strategy
* [ ] Bugs, bugs, bugs

### v0.27.0
* [ ] Bugs, bugs, bugs
